apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default-conf: |
    server {
        listen 80;
        location / {
                proxy_pass http://service1:8001;
        }
    }        
